stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script:
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install Flask
        - python3 app.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 ./test/pyunittest.py