stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script:
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install Flask
        - pip3 install flask_wtf
        - pip3 install wtforms
        - pip3 install wtforms.validators
        - pip3 install holidays
        - pip3 install datetime
        - pip3 install requests
        - pip3 install json
        - python3 ./app/calculator_form.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 -m test.pyunittest
